# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# syntax=docker/dockerfile:1
FROM node:lts-alpine AS builder
WORKDIR /app
# Install dependencies
COPY package.json package-lock.json ./
RUN npm ci
# Copy source and build
COPY . .
RUN npm run build

# Runtime image
FROM node:lts-alpine
WORKDIR /app
# Install production dependencies
COPY package.json package-lock.json ./
RUN npm ci --only=production
# Copy built files and dependencies
COPY --from=builder /app/build ./build

# Default command
CMD ["node", "build/index.js"]
